export type RealisationProject = {
  url: string;
  img: string;
  title: string;
  client: string;
  cat: string; // data-cat, space-separated
  sector: string; // data-sector, space-separated
  tech: string; // data-tech, space-separated
  type: string;
  desc: string;
  sectors: string[];
  expertises: string[];
  technologies: string[];
};

export const REALISATIONS: RealisationProject[] = [
  {
    url: "https://www.batipropre44.fr/",
    img: "/assets/proj-batipropre.jpg",
    title: "Site vitrine & référencement local",
    client: "Batipropre",
    cat: "site seo",
    sector: "artisan",
    tech: "wordpress seo-tools",
    type: "Site vitrine & référencement local",
    desc: "Site vitrine et référencement local pour l'entreprise de nettoyage, pensé pour rassurer et générer des demandes de devis sur sa zone d'intervention.",
    sectors: ["Artisan", "Services"],
    expertises: ["Création site Web", "SEO", "Audit & conseil"],
    technologies: ["WordPress"],
  },
  {
    url: "https://3dscanow.fr/",
    img: "/assets/proj-3dscanow.jpg",
    title: "Création de site internet",
    client: "3D Scanow",
    cat: "site",
    sector: "industrie",
    tech: "wordpress",
    type: "Création de site internet",
    desc: "Site présentant les services de numérisation et d'impression 3D, avec une architecture claire pour valoriser une expertise technique pointue.",
    sectors: ["Industrie", "Technologies"],
    expertises: ["Atelier UX", "Création site Web"],
    technologies: ["WordPress"],
  },
  {
    url: "https://aeg-construction.fr/",
    img: "/assets/proj-aeg.jpg",
    title: "Site corporate & réalisations",
    client: "AEG Construction",
    cat: "site",
    sector: "batiment",
    tech: "wordpress",
    type: "Site corporate & réalisations",
    desc: "Site corporate mettant en avant les réalisations et le savoir-faire de l'entreprise du bâtiment, pour crédibiliser la marque et capter de nouveaux chantiers.",
    sectors: ["Bâtiment", "Construction"],
    expertises: ["Création site Web", "SEO"],
    technologies: ["WordPress"],
  },
  {
    url: "https://www.atelierducerame.fr/",
    img: "/assets/proj-atelierducerame.jpg",
    title: "Site vitrine professionnel",
    client: "L'Atelier du Céramе",
    cat: "site",
    sector: "artisan",
    tech: "wordpress",
    type: "Site vitrine professionnel",
    desc: "Site vitrine chaleureux pour l'atelier de céramique, valorisant les créations et facilitant l'inscription aux ateliers.",
    sectors: ["Artisan", "Loisirs"],
    expertises: ["Atelier UX", "Création site Web"],
    technologies: ["WordPress"],
  },
  {
    url: "https://www.c2es.club/",
    img: "/assets/proj-c2es.jpg",
    title: "Site web & identité",
    client: "C2ES — Club d'entreprises",
    cat: "site",
    sector: "services",
    tech: "wordpress",
    type: "Site web & identité",
    desc: "Création du site du club d'entreprises, pensé pour fédérer les membres, présenter les événements et faciliter les adhésions.",
    sectors: ["Services", "Réseau"],
    expertises: ["Identité visuelle", "Création site Web"],
    technologies: ["WordPress"],
  },
  {
    url: "https://viniscope.fr/",
    img: "/assets/proj-viniscope.jpg",
    title: "Création de site internet",
    client: "Viniscope",
    cat: "site",
    sector: "evenementiel",
    tech: "wordpress",
    type: "Création de site internet",
    desc: "Site dédié à l'univers du vin et de l'événementiel, avec une identité soignée et une expérience de navigation immersive.",
    sectors: ["Événementiel", "Vin"],
    expertises: ["Atelier UX", "Création site Web", "SEO"],
    technologies: ["WordPress"],
  },
  {
    url: "https://www.ecylaos.fr/",
    img: "/assets/proj-ecylaos.jpg",
    title: "Site e-commerce",
    client: "eCylaos",
    cat: "site ecommerce",
    sector: "industrie",
    tech: "wordpress ecommerce",
    type: "Site e-commerce",
    desc: "Plateforme e-commerce de l'écosystème Cylaos, conçue pour la vente en ligne avec un parcours d'achat fluide et optimisé pour la conversion.",
    sectors: ["Industrie", "E-commerce"],
    expertises: ["Création site Web", "E-commerce", "SEO"],
    technologies: ["WooCommerce", "WordPress"],
  },
  {
    url: "https://libre-court.com/",
    img: "/assets/shots/libre-court.jpg",
    title: "Création de site internet",
    client: "Libre Court",
    cat: "site",
    sector: "tourisme",
    tech: "wordpress",
    type: "Création de site internet",
    desc: "Refonte complète du site de l'enseigne textile, pensé pour valoriser les collections et faciliter la prise de contact. Un design épuré, rapide et optimisé pour le référencement local.",
    sectors: ["Textile", "Commerce"],
    expertises: ["Atelier UX", "Création site Web", "SEO"],
    technologies: ["WordPress"],
  },
  {
    url: "https://www.e-cassini.fr/",
    img: "/assets/shots/e-cassini.jpg",
    title: "Site web & référencement",
    client: "e-Cassini",
    cat: "site seo",
    sector: "services",
    tech: "wordpress seo-tools",
    type: "Site web & référencement",
    desc: "Création d'un site vitrine professionnel accompagné d'une stratégie de référencement local pour gagner en visibilité sur les recherches métier.",
    sectors: ["Services"],
    expertises: ["Création site Web", "SEO", "Audit & conseil"],
    technologies: ["WordPress"],
  },
  {
    url: "https://www.alterpark.fr/",
    img: "/assets/shots/alterpark.jpg",
    title: "Refonte de site & SEO local",
    client: "AlterPark",
    cat: "site seo",
    sector: "tourisme",
    tech: "wordpress seo-tools",
    type: "Refonte de site & SEO local",
    desc: "Refonte du site et optimisation du référencement local pour développer la fréquentation et les réservations du parc de loisirs.",
    sectors: ["Tourisme", "Loisirs"],
    expertises: ["Atelier UX", "Création site Web", "SEO"],
    technologies: ["WordPress"],
  },
  {
    url: "https://sebertdavid-psychologue.com/",
    img: "/assets/shots/sebert.jpg",
    title: "Site vitrine professionnel",
    client: "David Sébert · Psychologue",
    cat: "site",
    sector: "sante",
    tech: "wordpress",
    type: "Site vitrine professionnel",
    desc: "Un site vitrine sobre et rassurant, pensé pour présenter la pratique et faciliter la prise de rendez-vous des patients.",
    sectors: ["Santé"],
    expertises: ["Création site Web", "SEO"],
    technologies: ["WordPress"],
  },
  {
    url: "https://www.lincubacteur.fr/",
    img: "/assets/shots/incubacteur.jpg",
    title: "Création de site internet",
    client: "L'Incubacteur",
    cat: "site",
    sector: "services",
    tech: "wordpress",
    type: "Création de site internet",
    desc: "Site présentant l'accompagnement et les programmes de l'incubateur, avec une architecture claire pour orienter porteurs de projet et partenaires.",
    sectors: ["Services", "Entrepreneuriat"],
    expertises: ["Atelier UX", "Création site Web"],
    technologies: ["WordPress"],
  },
  {
    url: "https://www.flamme-atlantique.fr/",
    img: "/assets/shots/flamme.jpg",
    title: "Site web & référencement local",
    client: "Flamme Atlantique",
    cat: "site seo",
    sector: "distribution",
    tech: "wordpress seo-tools",
    type: "Site web & référencement local",
    desc: "Site vitrine et référencement local pour renforcer la présence de l'entreprise sur sa zone de chalandise et générer des demandes de devis.",
    sectors: ["Distribution", "Énergie"],
    expertises: ["Création site Web", "SEO"],
    technologies: ["WordPress"],
  },
  {
    url: "https://www.prisma-technologies.fr/",
    img: "/assets/shots/prisma.jpg",
    title: "Site corporate & visibilité",
    client: "Prisma Technologies",
    cat: "site",
    sector: "industrie",
    tech: "wordpress",
    type: "Site corporate & visibilité",
    desc: "Site corporate moderne mettant en avant l'expertise industrielle de l'entreprise, avec une stratégie de visibilité ciblée.",
    sectors: ["Industrie"],
    expertises: ["Atelier UX", "Création site Web", "SEO"],
    technologies: ["WordPress"],
  },
  {
    url: "https://accent-beaute.com/",
    img: "/assets/shots/accent.jpg",
    title: "Site vitrine & Google My Business",
    client: "Accent Beauté",
    cat: "site",
    sector: "mode-beaute",
    tech: "wordpress",
    type: "Site vitrine & Google My Business",
    desc: "Site vitrine et optimisation de la fiche Google Business Profile pour attirer une clientèle de proximité et faciliter les réservations.",
    sectors: ["Beauté", "Bien-être"],
    expertises: ["Création site Web", "SEO"],
    technologies: ["WordPress"],
  },
  {
    url: "https://www.cote-nature-fleuriste.fr/",
    img: "/assets/shots/cotenature.jpg",
    title: "Création de site internet",
    client: "Côté Nature · Fleuriste",
    cat: "ecommerce site",
    sector: "distribution",
    tech: "woocommerce wordpress",
    type: "Création de site e-commerce",
    desc: "Boutique en ligne permettant la commande et la livraison de compositions florales, couplée à une mise en avant locale du commerce.",
    sectors: ["Distribution", "Commerce"],
    expertises: ["Création site Web", "E-commerce", "SEO"],
    technologies: ["WooCommerce", "WordPress"],
  },
  {
    url: "https://www.commissaire-a-la-transformation.fr/",
    img: "/assets/shots/commissaire.jpg",
    title: "Site web & identité de marque",
    client: "Le Commissaire à la Transformation",
    cat: "identite site",
    sector: "services",
    tech: "wordpress",
    type: "Site web & identité de marque",
    desc: "Création de l'identité visuelle et du site, pour une marque de conseil claire, crédible et différenciante.",
    sectors: ["Services", "Conseil"],
    expertises: ["Identité visuelle", "Atelier UX", "Création site Web"],
    technologies: ["WordPress"],
  },
  {
    url: "https://cylaos.fr/",
    img: "/assets/shots/cylaos.jpg",
    title: "Site web & stratégie digitale",
    client: "Cylaos",
    cat: "site seo",
    sector: "technologies",
    tech: "wordpress seo-tools",
    type: "Site web & stratégie digitale",
    desc: "Site et stratégie digitale pour l'éditeur de solutions RH, avec un travail de référencement pour capter une audience qualifiée.",
    sectors: ["Technologies", "RH"],
    expertises: ["Création site Web", "SEO", "Campagnes d’acquisition"],
    technologies: ["WordPress"],
  },
  {
    url: "https://astriddeplinval.fr/",
    img: "/assets/shots/astrid-de-plinval.jpg",
    title: "Site vitrine & référencement local",
    client: "Astrid de Plinval",
    cat: "site seo",
    sector: "sante",
    tech: "wordpress seo-tools",
    type: "Site vitrine & référencement local",
    desc: "Site vitrine élégant pour la sexologue et sexothérapeute, pensé pour rassurer, présenter l'accompagnement et faciliter la prise de rendez-vous des patients sur Nantes et sa région.",
    sectors: ["Santé", "Bien-être"],
    expertises: ["Atelier UX", "Création site Web", "SEO"],
    technologies: ["WordPress"],
  },
  {
    url: "https://www.tntvans.fr/",
    img: "/assets/shots/tnt-vans.jpg",
    title: "Site web & référencement",
    client: "T&T Vans",
    cat: "site seo",
    sector: "industrie",
    tech: "wordpress seo-tools",
    type: "Site web & référencement",
    desc: "Site de présentation des vans aménagés AVENTOURER, mettant en valeur les modèles, les options et la galerie photo, avec une stratégie de visibilité pour générer des demandes de devis.",
    sectors: ["Industrie", "Automobile"],
    expertises: ["Création site Web", "SEO", "Atelier UX"],
    technologies: ["WordPress"],
  },
];

export const FILTER_DIMENSIONS = {
  exp: {
    label: "Expertises",
    options: [
      { val: "all", label: "Tous" },
      { val: "ux", label: "Atelier UX" },
      { val: "audit", label: "Audit & conseil" },
      { val: "acquisition", label: "Campagnes d'acquisition" },
      { val: "site", label: "Création site Web" },
      { val: "ecommerce", label: "E-commerce" },
      { val: "email", label: "Email marketing" },
      { val: "identite", label: "Identité visuelle" },
      { val: "seo", label: "SEO" },
      { val: "analytics", label: "Web Analytics" },
    ],
  },
  sector: {
    label: "Secteurs d'activités",
    options: [
      { val: "all", label: "Tous" },
      { val: "banque", label: "Banque & assurance" },
      { val: "conso", label: "Biens de conso & Agro" },
      { val: "art", label: "Art, culture & événementiel" },
      { val: "distribution", label: "Distribution & retail" },
      { val: "ecommerce", label: "E-Commerce" },
      { val: "immobilier", label: "Immobilier & construction" },
      { val: "industrie", label: "Industrie" },
      { val: "institutions", label: "Institutions & associations" },
      { val: "mobilite", label: "Mobilité & transport" },
      { val: "mode-beaute", label: "Mode & beauté" },
      { val: "sante", label: "Santé & médical" },
      { val: "services", label: "Services & consulting" },
      { val: "technologies", label: "Technologies & logiciels" },
      { val: "tourisme", label: "Tourisme, loisirs & outdoor" },
    ],
  },
  tech: {
    label: "Technologies & outils",
    options: [
      { val: "all", label: "Tous" },
      { val: "wordpress", label: "WordPress" },
      { val: "woocommerce", label: "WooCommerce" },
      { val: "seo-tools", label: "SEO & Analytics" },
    ],
  },
} as const;

export type FilterDim = keyof typeof FILTER_DIMENSIONS;
